select 
brand,
{{store_name('store')}},
campaignId as campaign_id,
cast(null as string) as flow_id,
AdgroupId as adgroup_id, 
AdId as ad_id, 
cast(null as string) as product_id,
cast(null as string) as sku,
date(timeperiod) as date,
exchange_currency_rate,
exchange_currency_code,
'Shopify' as platform_name,
'Bing' as ad_channel,
'Bing' as campaign_type, 
'Bing' as ad_type,
sum(cast(clicks as int)) clicks,
sum(cast(impressions as int)) impressions,
sum(cast(conversions as int)) conversions,
sum(cast(conversions as int)) quantity,
sum(cast(spend as numeric)) as spend,
sum(cast(revenue as numeric)) as sales,
sum(cast(null as numeric)) email_deliveries,
sum(cast(null as numeric)) email_opens,
sum(cast(null as numeric)) email_unsubscriptions
from {{ ref('BingAdPerformanceReport') }}
group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15